# SPDX-License-Identifier: Apache-2.0
{{- if .Values.mcpServers.gemara.enabled }}
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: gemara-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gide.labels" . | nindent 4 }}
spec:
  deployment:
    image: {{ .Values.mcpServers.gemara.image }}
    cmd: gemara-mcp
    args:
      - serve
    port: 3000
  transportType: stdio
  stdioTransport: {}
{{- end }}
